/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Link } from "./utils/types";
export namespace Components {
    interface StFooter {
        "copy": string;
        "doStuff": () => Promise<void>;
        "links": Link[];
    }
    interface StModal {
        "body": string;
        "footer": string;
        "header": string;
        "modalName": string;
    }
}
declare global {
    interface HTMLStFooterElement extends Components.StFooter, HTMLStencilElement {
    }
    var HTMLStFooterElement: {
        prototype: HTMLStFooterElement;
        new (): HTMLStFooterElement;
    };
    interface HTMLStModalElement extends Components.StModal, HTMLStencilElement {
    }
    var HTMLStModalElement: {
        prototype: HTMLStModalElement;
        new (): HTMLStModalElement;
    };
    interface HTMLElementTagNameMap {
        "st-footer": HTMLStFooterElement;
        "st-modal": HTMLStModalElement;
    }
}
declare namespace LocalJSX {
    interface StFooter {
        "copy"?: string;
        "links"?: Link[];
    }
    interface StModal {
        "body"?: string;
        "footer"?: string;
        "header"?: string;
        "modalName"?: string;
    }
    interface IntrinsicElements {
        "st-footer": StFooter;
        "st-modal": StModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "st-footer": LocalJSX.StFooter & JSXBase.HTMLAttributes<HTMLStFooterElement>;
            "st-modal": LocalJSX.StModal & JSXBase.HTMLAttributes<HTMLStModalElement>;
        }
    }
}
